FROM golang:latest

COPY . /backend

WORKDIR /backend
RUN go mod init backend
RUN go mod tidy
RUN go build -o backend .

ENV DB_USERNAME=root
ENV DB_PASSWORD=root
ENV DB_HOST=dbhotel
ENV DB_PORT=3306
ENV DB_DATABASE=hotelapp

EXPOSE 8080

CMD ["/backend/backend"]